name: igpdoc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - django=5.*
  - djangorestframework
  - django-cors-headers
  - psycopg2
  - gdal
  - geos
  - proj
  - shapely
  - postgresql
  - pip
  - python-dotenv
  - djangorestframework-gis
  - postgis